name: Macos daily check

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Macos daily check
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Install building tools
        run: brew install node python ninja nasm git

      - name: Clone the repo
        run: git clone https://github.com/devraymondsh/libnode-distributable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Run the script
        env:
          CC: "sccache cc"
          CXX: "sccache c++"
          ARCH: ${{ matrix.arch }}
          SCCACHE_GHA_ENABLED: "true"
        run: cd libnode-distributable && node index.js

      - name: Find the shared library
        run: find libnode-distributable/node -name libnode.so\* -not -name '*.TOC' -not -name '*.toc' -exec ls {} \;
