name: Check for newer versions and publish

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Check for newer versions of Rust and update
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
    steps:
      - name: Update system
        run: apt-get update && apt-get --yes upgrade

      - name: Install Nodejs 21 repo
        run: apt-get install --yes ca-certificates curl gnupg && curl -sL https://deb.nodesource.com/setup_21.x | bash - && apt-get update

      - name: Install building tools
        run: apt-get install --yes git python3 python3-pip gcc g++ make ninja-build nodejs npm nodejs-dev node-gyp libssl-dev

      - name: Clone the repo
        run: git clone https://github.com/devraymondsh/libnode-distributable

      - name: Run the script
        run: cd libnode-distributable && node index.js
