name: Check for newer versions and publish

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Check for newer versions of Rust and update
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
    steps:
      - name: Update system
        run: apt-get update && apt-get --yes upgrade

      - name: Install building tools
        run: apt-get install --yes git python3 python3-pip gcc g++ make ninja-build nodejs

      - name: Clone the repo
        run: git clone https://github.com/devraymondsh/libnode-distributable

      - name: Run the script
        run: node index.js
