name: Windows daily check

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Windows daily check
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, amd64_arm64]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - uses: MinoruSekine/setup-scoop@v3
        with:
          buckets: extras
          update_path: true
          run_as_admin: true
          scoop_update: true

      - name: Install building tools
        run: scoop install nodejs python ninja nasm git

      - name: Clone the repo
        run: git clone https://github.com/devraymondsh/libnode-distributable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Run the script
        env:
          ARCH: ${{ matrix.arch }}
          SCCACHE_GHA_ENABLED: "true"
        run: cd libnode-distributable ; node index.js

      - name: Find the shared library
        run: dir /s libnode-distributable\node\out\Release\libnode.dll
