name: Windows

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, amd64_arm64]
    steps:
      - uses: actions/checkout@v4

      - run: |
          "$([Environment]::OSVersion.VersionString) $(('x86', 'x64')[[Environment]::Is64BitOperatingSystem])"
      # - name: Setup ccache
      #   uses: actions/cache@v4
      #   with:
      #     key: ${{ github.workflow }}-${{ matrix.arch }}
      #     path: C:\.ccache

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - uses: MinoruSekine/setup-scoop@v3
        with:
          update_path: true
          run_as_admin: true
          scoop_update: true

      - name: Install building tools
        run: scoop install git nodejs python ninja nasm

      - name: Run the script
        env:
          ARCH: ${{ matrix.arch }}
        run: node index.js

      - name: Find the shared library
        run: dir node\out\Release\node.lib
